### ISSUE TITLE
GLIBC_2.28 not found on Ubuntu linux 18.04.5 LTS

### ISSUE THREAD

**Issue by dckc** [agoric-labs/Pledger#8]
I grabbed the current release for linux, unzipped it, ran `./pledger`... the systray icon comes up, but when I choose "Pledger Dashboard..." I get:

```
/home/connolly/Desktop/Pledger-linux-x64/resources/app/node_modules/@pledger/plugin-agoric-app/node_modules/node-lmdb/index.js:1
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/connolly/Desktop/Pledger-linux-x64/resources/app/node_modules/@pledger/plugin-agoric-app/node_modules/node-lmdb/build/Release/node-lmdb.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812) 
Exited 1
```

when I choose "Open Agoric Wallet" I get ERR_CONNECTION_REFUSED.

Release 18.04.5 LTS (Bionic Beaver) 64-bit

```
$ uname -a
Linux jambox 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by michaelfig** [comment]
The zip file probably only works on Ubuntu 20.04 and later.  Please use the snap version instead.

We need documentation for how to install on each platform.  I'll make an issue.

If you have problems with the snap as well, feel free to reopen.

**Comment by dckc** [comment]
The snap works fine.
